<div class="forumDispatch">
<?php echo $this->image("regel1investor-screen.png", null, null, "forumDispatchRegel1ForumScreen");?>
<h1>Regel1Investor.de - Regel Nummer 1 Forum</h1>
<p>

Allen Rule1Tool-Nutzern empfehlen wir das Forum unseres Partners Regel1Investor.de. 

Hier finden Sie viele nützliche Beiträge rund um Regel Nummer 1 und Payback Time und 
können außerdem mit anderen Mitgliedern über aktuelle Geschehnisse diskutieren.

</p>
<a class="abutton blue large" style="float:right;" href="http://www.regel1investor.de/" target="blank">Zum Forum &raquo;</a>
</div>
