<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
<head>
	<?= $this->headTitle() ?>
    <?= $this->headScript() ?>
    <?= $this->headStyle() ?>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta name="description" content="" />
	<meta name="robots" content="index,follow" />		
</head>
<body style="margin:0px;padding:0px;background-color:#f4f4f4">
<style>
a{
	color:#226cb7;
	text-decoration:none;
}
a:hover{
	color:#226cb7;
	text-decoration:underline;
}
</style>

<table width="100%" bgcolor="#f4f4f4" cellspacing=0 cellpadding=5 style="color: #333;
	font-family: Tahoma, Verdana, sans-serif;
	font-size: 12px;
	line-height: 1.4em;">
<tr>
<td align="center">
<table width="100%" bgcolor="#ffffff" cellspacing="0" cellpadding="0" style="border:1px solid #b9b9b9; max-width:630px;">
<tbody>
	<tr>
	<td bgcolor="#ffffff">
	<img border=0 src="<?php echo $this->baseUrlShort();?>/public/images/logo.jpg" style="margin-left:10px;margin-top:10px;" alt="" />
	</td>
	</tr>
	
	<tr>
	<td style="padding:2px 10px 5px;">
	<?php echo $this->layout()->content;?>
	</td>
	</tr>
	

</tbody>
</table>
</td>
</tr>
	<tr>
	<td align="center" bgcolor="#f4f4f4" style="color:#b9b9b9; font-size:11px;padding:10px;" align="center">&copy; Rule1Tool 2011. <?php echo $this->translate("Alle Rechte vorbehalten.");?></td>
	</tr>
</table>
</body>
</html>