


<div class="forumDispatch">
<?php echo $this->image("logo.png", null, null, "donateBoxR1logo");?>

<h1>Rule1Tool needs you!</h1>
<p>

Rule1Tool ist kostenlos und soll es auch bleiben! 
Wir verzichten bewusst auf Werbeeinblendungen, 
um Ladezeiten möglichst gering zu halten und die Benutzung so angenehm wie möglich zu gestalten.<br/>
<br/>
Wir haben viel Aufwand in die Entwicklung von Rule1Tool gesteckt &ndash; und das haben wir gerne getan!<br/>
<br>
Dennoch entstehen uns durch den Betrieb von Rule1Tool laufende Kosten: 
allen voran sind das die Serverkosten &ndash; und diese werden mit steigenden Besucherzahlen 
(die uns natürlich mehr als freuen) in Zukunft weiter zunehmen.<br>
<br>
Um die Seite auch in Zukunft weiter betreiben zu können, freuen wir uns über ein paar kleine Spenden &ndash; 
jeder Euro ist willkommen.<br>
<br>
Vielen Dank,<br>
Euer Rule1Tool-Team

</p>
<center>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="RVD2KSSMM3FWQ">
<input type="image" src="https://www.paypal.com/de_DE/DE/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="Jetzt einfach, schnell und sicher online bezahlen – mit PayPal.">
<img alt="" border="0" src="https://www.paypal.com/de_DE/i/scr/pixel.gif" width="1" height="1">
</form>
</center>
</div>
