<style type="text/css" media="all">

p.quote {
	overflow: hidden;
	padding: 0 0;
	text-align: center;
	font-family: Georgia, serif;
	font-size:1.4em;
	line-height:1.4em;
	margin:15px 0;

}
p.quote span.author{

	font-size:0.6em;

}

</style>


<h1>Payback Time: Making Big Money Is the Best Revenge!</h1>
<h2>Deutscher Titel: "Jetzt aber!: Erfolgreich anlegen in 8 Schritten"</h2>
  <p class="quote">
  I'm about to teach you the very best strategy for investing &ndash; the one strategy worth pursuing regardless of how much time, money, and effort you think you have available.
  <span class="author">Phil Town</span>
  </p>

<p>
Wie auch in "Regel Nummer 1" geht es in "Payback Time" im Kern darum, <strong>wunderbare und unterbewertete Unternehmen zu finden und zu besitzen</strong>. Phil Town selbst sieht Payback Time als eine Art Prequel zu Rule #1, da es hier noch mehr ums Investieren als um das Handeln geht. Für alle die bereits Regel Nr. 1 gelesen haben, ist Payback Time eine wirklich gute Ergänzung und Erweiterung.
</p>
  <?php echo $this->image("paybacktime.jpg", "Payback Time von Phil Town", null, "right")?>

<h1>1. Unternehmen finden</h1>
<p>
Wie schon in Regel Nr. 1 empfiehlt Phil sich Unternehmen zu suchen, die man bereits kennt bzw. deren Branchen man auf die ein oder andere Art bereits kennt. Siehe hierzu: Wie finde ich mein wunderbares Unternehmen?
</p>
<p>
Um relativ bequem eine Vorauswahl an Unternehmen zu treffen, empfehlen sich sog. <strong>"Stock Screener"</strong>. Bei diesen hat man die Möglichkeit, nach verschiedenen Kriterien, wie z.B. Branche, ROIC oder Wachstumsraten, Unternehmen zu suchen. Als besonders einfache und schnelle Lösung empfehlen sich der 
<a href="http://www.google.com/finance/stockscreener">Google Finance Stock Screener</a> oder alternativ <a href="http://finviz.com/screener.ashx">Finviz Stock Screener</a> .
</p>

<h1>2. Unternehmen analysieren</h1>
<p>
In Payback Time rückt die reine Kennzahlen-Analyse im Vergleich zu Regel Nummer 1 etwas in den Hintergrund, da Phil Town eine stärke Betonung auf die 3 M's (Meaning, Moat und Management) legt. <br/>
Allen voran betont er die Wichtigkeit eines <strong>Burggrabens</strong>/Alleinstellungsmerkmals (Moat). Hier sollte man sich nichts vormachen, sondern realistisch an die Sache gehen und sich durchaus fragen, ob ein anderes Unternehmen mit genügend Geld das Gleiche machen und somit in direkte Konkurrenz treten könnte. In diesem Zusammenhang rät Phil grundsätzlich zur Vorsicht bei Technologie-Unternehmen, da bei diesen besonders schnell aus Gewinnern Verlierer (und umgekehrt) werden können.
</p>
<h2>Wachstumskennzahlen // The Big Five</h2>
<p>
Die Wachstumskennzahl (ROIC, Eigenkapital, Umsatz, Gewinn, Cashflow) werden wie in Regel Nr. 1 berechnet und alle Werte sollten bei mind. 10 % liegen. Dabei betont Phil Town aber, dass <strong>Kontinuität wichtiger ist als absolute Höhe</strong>; also lieber 8% Durchgängig, als stark schwankende Werte.
</p>

<h2>Empfehlungspreis und Margin of Safety (MOS)</h2>
<p>
Der Empfehlungspreis und MOS werden dann wie in Regel Nr. 1 berechnet, siehe hierzu: Aktuellen Empfehlungspreis und Sicherheitspolster berechnen.
</p>
<p>
Wie auch schon in Regel Nummer 1 gilt es wieder <strong>1 Euro für 50 Cent</strong> zu kaufen, daher wird auch wieder ein Sicherheitspolster von 50 % auf den Empfehlungspreis angesetzt. Einzige Ausnahme ist, wenn man das Unternehmen und die Branche besonders gut kennt: dann kann auch bei geringeren Sicherheitspolster gekauft werden. Aber für den Anfang ist es sicherlich ratsam, konsequent bei den 50% zu bleiben.
</p>

<h2>Schulden</h2>
<p>
Zusätzlich sollte man noch die Schulden des Unternehmens betrachten. Gut ist es, wenn diese theoretisch innerhalb von drei Jahren durch den Gewinn bezahlbar wären; im Idealfall hat das Unternehmen natürlich keine Schulden. Aber <strong>Schulden sind nicht immer nur negativ</strong>, daher gilt es zu prüfen, zu welchem Zweck die Schulden aufgenommen wurden. Wurden die Schulden nämlich für Investitionen verwendet, die den ROIC in den nächsten Jahren erhöhen, so sind dies durchaus akzeptable Schulden.
</p>

<h2>Hausaufgabe: Informieren Sie sich!</h2>
<p>Man kann es nicht oft genug sagen (und in Payback Time tut dies Phil auch viel öfters als in Rule #1): es ist von großer Bedeutung, dass man sich ausführlich über das Unternehmen und die Branche informiert! Wer sich nicht richtig informiert, kann keine Prognosen über die Zukunft des Unternehmens abgeben (also auch keinen korrekten Empfehlungspreis berechnen) und wird Veränderungen in der Branche oder im Unternehmen nicht rechtzeitig mitbekommen! </br>
Um dies zu verdeutlichen schlägt Phil Town folgende <strong>"Hausaufgaben"</strong> vor:
</p>
<ol>
<li>Quartals-Telefonkonferenz mit CEO und Analysten mithören bzw. nachlesen</li>
<li>Quartalsbericht lesen</li>
<li>Jahresbericht inkl. Brief des CEOs lesen</li>
<li>News zum Unternehmen lesen</li>
<li>Top Mitbewerber im Auge behalten</li>
<li>Branchennews lesen</li>
</ol>


<h2>Ergänzung um Payback Time Analyse</h2>
<p>Ergänzend zur Regel Nummer 1 Analyse mit Berechnung des MOS, führt Phil Town in Payback Time eine weitere Analyse ein, um einen fairen Einstiegspreis zu bestimmen: die sog. Payback Time Analyse.<br/>
Dabei gilt es folgendes Szenario zu erörtern: Angenommen, man würde das ganze Unternehmen kaufen, wie lange würde es dauern, bis man durch Auszahlung des Unternehmensgewinn den Kaufpreis wieder zurück hat? Diese <strong>"Rückzahlungsdauer" (Payback Time)</strong> sollte unter 10 Jahren liegen, wobei 6 Jahre oder weniger exzellent wären.
</p>
<p>
Die Berechnung der Payback Time ist relativ einfach: man macht eine Zinseszinsrechnung mit dem aktuellen Gewinn/Ertrag ("Zinssatz" ist die in der Regel Nr. 1 Analyse berechnete Wachstumsrate) solange bis man die aktuelle <strong>Marktkapitalisierung</strong> (Anzahl der Aktien * Aktienkurs) erreicht hat. Auf diese Weise kann man sowohl den aktuellen Aktienkurs als auch den MOS (hier berechnet man die Marktkapitalisierung einfach mit Hilfe des MOS) überprüfen und erhält so eine gute Hilfe beim Finden des richtigen Einstiegskurses. Liegt die Payback Time beim potentiellen Einstiegskurs über 10 Jahre, so sollte man in der Regel lieber auf niedrigere Kurse warten. Die Geduld wird sich in Form von höheren Renditen später auszahlen!
</p>

<h1>3. Unternehmen kaufen und verkaufen</h1>

<p class="quote">You buy when there's a lot of fear. You sell when there's a lot of greed.</p>

<p>
Bevor wir zum Kaufen und Verkaufen nach Payback Time kommen, sollte noch mal betont werden, wie wichtig eine gute Unternehmensanalyse ist. Phil bringt hier ein sehr gutes Zitat von Abraham Lincoln an: 
</p>
<p class="quote">Give me six hours to chop down a tree and I will spend the first four sharpening the axe.
<span class="author">Abraham Lincoln</span></p> 

<h2>Stockpiling Strategy</h2>
<p>
In schwierigen Marktzeiten, in denen es bergab oder vor allem seitwärts geht, kann die Anwendung von Chat-Tools &ndash; wie in Regel Nummer 1 &ndash; schwierig sein, da man wiederholt mit leichten Verlusten oder eher geringen Gewinnen aussteigt um kurze Zeit später wieder einzusteigen; sodass man am Ende viel Geld für Börsengebühren ausgegeben hat. Daher empfiehlt Phil Town in Payback Time sogenanntes <strong>"stockpilling"</strong> durchzuführen. Im Grunde heißt das nur, dass man wiederholt (!) unter dem MOS kauft; fällt die Aktie nach einem Kauf, so verkauft man nicht, sondern kauft noch mehr! Dadurch senkt man den durchschnittlichen Einstiegspreis und erhöht so seinen Gewinn. 
</p>

<p class="quote">
The purpose of stockpiling a business is to maximize our return on investment with the least effort and least risk possible.
</p>
<p>
Hierzu führt Phil ein (vielleicht etwas übertriebenes) Beispiel im Buch an:
</p>
<p>
Angenommen man hätte den Empfehlungspreis eines Unternehmens A auf 20 USD kalkuliert und ein Budget von 60000 USD. Man wartet nun bis der Aktienkurs den MOS (10 USD) erreicht hat und kauft dann; und zwar 2000 Aktien für je 10 USD (=20000 USD). Nun fällt der Kurs weiter auf 5 USD und man kauft 4000 Aktien für je 5 USD (=20000 USD). Anschließend fällt der Aktienkurs noch weiter und man kauft schlussendlich 20000 Aktien zum Preis von je 1 USD (=20000 USD). <br/>
Jetzt hat man sein Budget zu 100% investiert und zusammen 26000 Aktien erworben. Nach fünf Jahren erreicht der Aktienkurs den berechneten Empfehlungspreis von 20 USD und man verkauft alle Aktien; also 26000 * 20 USD = 520.000 USD. D.h. abzüglich des Einstandspreises hat man einen Gewinn von 460.000 USD innerhalb von fünf Jahren gemacht, was einer Rendite von 54 % entspricht. Ganz ordentlich oder?<br/>
Das Beispiel zeigt, dass dieser außerordentliche Gewinn nur möglich war, weil man später sehr günstig Nachgekauft hat (20000 Aktien zu je 1 USD!).
</p>
<p>
Klar sollte sein, wer stockpilling betreibt, sollte sich extrem sicher beim MOS und dem zukünftigen Wachstum sein, denn einen doppelten Boden, wie in Regel Nummer 1 die Chart-Tools, gibt es hier nicht. Wer investieren will, muss auch zum Investor werden und seine Hausaufgaben erledigen!
</p>
<h2>Money Management</h2>
<p>
Wiederholt Unternehmen kaufen wenn die Kurse weiter fallen, ist nur möglich, wenn man entweder bisher nur einen Teil des eigenen Kapitals investiert hat oder wenn man einen konstanten Zustrom an Kapital hat (monatliche Sparrate). 
Daher sollte man nicht gleich komplett einsteigen: Phil empfiehlt für <strong>die ersten drei Käufe jeweils 25 % des Kapitals</strong>, danach soll man je nach Marktlage und Kapitalzufluss, den Rest auf weitere Käufe verteilen. Dabei sind zwei grundlegende Dinge zu beachten: 
</p>
<ol>
<li>als Regel Nummer 1 Investoren kaufen wir niemals über dem MOS (der MOS kann aber zwischen 20 - 50 % variieren je nach dem wie gut man eine Branche und Unternehmen kennt) und</li>
<li>man sollte auf die Transaktionsgebühren achten; lieber weniger Käufe machen und so Gebühren sparen, als viele kleine Transaktionen zu machen und dann vielfach Gebühren zu bezahlen.</li>
</ol>

<h2>Anhand von Charts optimale Kauf- und Verkaufszeitpunkte bestimmen</h2>
<p>
Man könnte zwar auch einfach zu bestimmten Zeitpunkten (z.B. monatlich) Aktien kaufen, aber um noch besser Trends erkennen und von ihnen profitieren zu können, empfiehlt Phil Town auch in Payback Time Chart-Technik anzuwenden. 
Diesmal ist aber etwas mehr Handarbeit gefragt als in Regel Nummer 1, denn die benutzten Werkzeuge werden meist nicht direkt von Websites dargestellt.
</p>
<p>
Wenn man sich eine Chart anguckt, kann man relativ einfach einen <strong>Trendkanal</strong> (<a href="http://www.aktien-handel.info/technische-aktienanalyse/trendlinien-und-trendkanaele.htm">kurze Erklärung</a>) und sog. <strong>Unterstützungs- und Widerstandszonen</strong> (<a href="http://www.aktien-handel.info/technische-aktienanalyse/unterstuetzung-wiederstand-bei-aktien.htm">kurze Erklärung</a>) (im Buch "Floors and Ceilings (FAC)" genannt) erkennen. Anhand dieser kann man eine wahrscheinliche, kurzfristige Entwicklung des Aktienkurses vorhersagen. Dieses Wissen wird dann genutzt, <strong>um zu einem möglichst geringen Preis wiederholt Aktien zu kaufen</strong>.
</p>
<p class="quote">Using the FACs correctly is icing on the cake, not the cake itself.</p>
  <?php echo $this->image("jetzt_aber_erfolgreich_anlegen_in_8_schritten.jpg", "Jetzt aber!: Erfolgreich anlegen in 8 Schritten von Phil Town", null, "right")?>

<h1>Fazit</h1>
<p>
Wir denken, dass Payback Time von Phil Town sowohl ein gutes Buch für Einsteiger als auch für Regel-Nummer-1-Investoren ist. Es bringt dem Leser <strong>fundamentale Investment-Prinzipien</strong> bei und legt so eine soliden Grundstein für erfolgreiche Investments.
</p>
<p>
Natürlich gilt auch hier, dass es in der Realität meist schwieriger ist, als im Buch beschrieben. Aber genau deshalb gibt es Rule1Tool! <br/>
</p>
<p>
Rule1Tool hat sich zum Ziel gesetzt, sowohl "Payback Time"- als auch "Regel Nummer 1"-Lesern die besten Hilfemittel zur Verfügung zu stellen um Ihren Investment-Erfolg zu maximieren.
</p>

<p>
<?php echo $this->link(
			$this->url(
				array(
					"language" => Zend_Registry::get('Zend_Locale')->getLanguage()), 
					"tour"), 
				$this->translate("Zur Tour &raquo;"),"abutton blue large");?>
				 
<?php 
echo $this->link(
		$this->url(array("language" => Zend_Registry::get('Zend_Locale')->getLanguage()),
		 "user_register"), $this->translate("Zur Registrierung &raquo;"),"abutton blue large");?> 

</p>

<h1>Weiterführende Links</h1>
<ul>
<li><a href="http://www.regel1investor.de">Deutsches Forum zu Regel Nummer 1 und Payback Time</a></li>
<li><a href="http://www.amazon.de/Jetzt-aber-Erfolgreich-anlegen-Schritten/dp/3941493264">Bei Amazon kaufen</a></li>
<li><a href="http://www.paybacktime.com/">Website von Phil Town</a></li>
<li><a href="http://en.wikipedia.org/wiki/Phil_Town">Wikipedia-Artikel über Phil Town</a></li>
</ul>
