<style type="text/css" media="all">

p.quote {
	overflow: hidden;
	padding: 0 0;
	text-align: center;
	font-family: Georgia, serif;
	font-size:1.4em;
	line-height:1.4em;
	margin:15px 0;

}
p.quote span.author{

	font-size:0.6em;

}

</style>


  <h1>Regel Nummer 1 / Rule #1: Einfach erfolgreich anlegen!</h1>
  <?php echo $this->image("Regel-Nummer-1.jpg", "Regel Nummer 1 von Phil Town", null, "right")?>
  <p><strong>Phil Town</strong> hat mit seinem Buch <strong>"Regel Nr. 1"</strong> eine Art Bibel für private 
  Value Investoren geschaffen: basierend auf den bekannten Ansätzen von <strong>Benjamin Graham</strong> und 
  <strong>Warren Buffett</strong> schafft Town eine für den Einsteiger verständliche Investment-Methode mit 
  klaren Regeln. Ziel: Wer die Regeln einhält wird mind. 15 % jährliche Rendite erzielen!</p>
  <p class="quote">
  Regel eins lautet: Verliere niemals Geld. Regel zwei lautet: Vergesse nie Regel eins.
  <span class="author">Warren Edward Buffett</span>
  </p>
 <h2>Finden Sie wunderbare Unternehmen, die Sie lieben!</h2>

<p>
Im Gegensatz zu anderen Investment-Strategien wird bei <strong>Rule #1</strong> auf eine starke Bindung 
zum Unternehmen gesetzt. Phil Town empfiehlt: <strong>"Seien Sie stolz auf Ihren Besitz!"</strong> <br />
Er beschreibt, dass man sich Unternehmen suchen soll, die man bereits liebt. Das klingt erst einmal komisch, 
ist aber sehr logisch, wenn man beachtet, dass ein kleiner, privater Anleger nicht die Zeit für ausgiebige 
Recherchen zu x-vielen Unternehmen hat. Vielmehr sollte man sich auf die Unternehmen konzentrieren die man 
bereits kennt. Auch wenn einem im ersten Moment kaum Unternehmen einfallen werden, so wird man 
in Zukunft viel aufmerksamer durch die Welt gehen und viel öfters potentielle Unternehmen entdecken.
</p>

<h1>Wie finde ich mein wunderbares Unternehmen?</h1>
<p>Phil Town schlägt vor, sich Fragen zu drei Bereichen zu stellen und daraus potentielle Unternehmen herzuleiten:</p>
<ul>
<li>Leidenschaft (Was tun Sie gerne (beruflich oder in der Freizeit)?)</li>
<li>Talent (Worin sind Sie wirklich gut?)</li>
<li>Geld (Was tun Sie, um Geld zu verdienen, und wofür geben Sie Ihr Geld aus?)</li>
</ul>
<p>
Nach dieser Selbst-Analyse sollte der Anleger ein oder mehrere Unternehmen gefunden haben, 
die er versteht und gerne besitzen würde. Wenn nicht, dann sollte man sich noch einige Zeit geben und 
aufmerksam durch die Welt spazieren, einige Magazine kaufen oder Freunde befragen.
</p>

<h1>Analyse eines Regel-1-Unternehmens</h1>

<p>Die eigentliche Analyse teilt Phil Town in <strong>"Regel Nummer Eins"</strong> in vier Bereiche:</p>
<ul>
<li>Meaning (Bedeutung)</li>
<li>Moat (Burggraben)</li>
<li>Management</li>
<li>Margin of Safety (MOS) (Sicherheitspolster)</li>
</ul>
<h2>Den Zukünftigen Unternehmenswert berechnen</h2>
<p>Anhand von 5 Kennzahlen (die sog. "Big Five") wird der aktuelle Zustand des Unternehmens ermittelt:</p>
<ul>
<li>ROIC (Return on Investment Capital)</li>
<li>Umsatzwachstum</li>
<li>Earnings per Share (EPS) Wachstumsrate</li>
<li>Eigenkapitalwachstum</li>
<li>Free Cash Flow Wachstum</li>
</ul>
<p>
Basierend auf der Annahme, dass Unternehmen, die in der Vergangenheit konstant gewachsen sind, 
dies auch in Zukunft tun werden, werden alle Unternehmen ausgesiebt, die nicht mind. 10 % jährlich 
innerhalb der letzten 10 Jahre gewachsen sind. Natürlich sollte man nicht dem Trugschluss unterliegen, 
dass nur weil ein Unternehmen die letzten 10 Jahre stetig gewachsen ist, dies auch in Zukunft so sein wird. 
Aber dennoch erhöht dies die Wahrscheinlichkeit auch in Zukunft zu wachsen enorm und macht es uns somit 
wesentlich einfacher wunderbare Unternehmen zu finden.
</p>
<h2>Wachstum für die nächsten 10 Jahre ermitteln</h2>
<p>Jetzt muss man ermitteln, wie stark ein Unternehmen in den nächsten 10 Jahren wachsen wird, 
denn davon ist der zukünftige Aktienkurs abhängig, und somit auch der Regel-1-Einstiegskurs 
(da die Börsenkurse immer die Zukunftsprognosen widerspiegeln). Laut Phil Town sollte man hierzu 
am besten das <strong>Eigenkapitalwachstum</strong> der letzten 10 Jahre betrachten: 
wenn das Eigenkapital wächst, können auch die Investitionen wachsen &ndash; und somit die Zukunftsaussichten.
</p>
<h2>Aktuellen Empfehlungspreis und Sicherheitspolster berechnen</h2>
<p>
Anschließend wird mit einer nicht ganz so einfachen Rechnung 
(wobei Regel Nummer 1 hier eine clevere Überschlagsmethode bietet) berechnet zu welchem Preis das Unternehmen 
in 10 Jahren gehandelt werden wird. Danach rechnet man den zukünftigen Preis zurück auf die Gegenwart und zieht 
dabei die angepeilte Rendite ab (15 % jährlich). So bekommt man den sog. "Empfehlungspreis", dieser spiegelt 
den aktuellen Wert eines Unternehmens wider.
</p>
<h2>Achtung: Schnäppchenjäger!</h2>
<p>
Aber jetzt kommt das Beste: Man kauft nicht einfach so zum Empfehlungspreis, 
sondern man macht es wie Warren Buffett und kauft <strong>1 Dollar für 50 Cent</strong>!  
Das ist dann der sog. <strong>MOS</strong> (Margin of Safety oder dt. Sicherheitspolster). 
Damit soll man die Sicherheit haben &ndash; treu dem Motto von Regel Nummer 1 &ndash; niemals Geld zu verlieren.
</p>
<h2>Mit Charttechnik sich den großen Jungs anschließen</h2>
<p>
Damit ist man aber noch nicht fertig. Phil Town empfiehlt in "Regel Nummer 1" <strong>drei Werkzeuge</strong>, 
deren Einstellungen auf wissenschaftlichen Tests und seinen Erfahrungen basieren:
</p>
<ul>
<li>MACD</li>
<li>Stochastik-Indikator</li>
<li>gleitender Durchschnitt</li>
</ul>
<p>Im Prinzip ist die Anwendung der Werkzeug recht simpel, zumindest wenn man ein Programm gefunden hat, 
dass die entsprechenden Werkzeuge bietet und richtig abbildet:</p>
<ul>
<li>Kaufen wenn alle Werkzeuge auf "kaufen" zeigen</li>
<li>Verkaufen wenn MACD und Stochastik-Indikator auf "verkaufen" zeigen 
UND entweder am Folgetag die Aktie stagniert bzw. fällt oder auch der gleitende Durchschnitt auf "verkaufen" zeigt</li>
</ul>
<p>Befolgt man die Signale der Werkzeuge, so soll man in der Lage sein, dass <strong>Verhalten der 
großen Investoren zu sehen</strong> und sowohl positive als auch negative Chartentwicklungen frühzeitig zu bemerken.
Dies beruht auf der Tatsache, dass große Investoren oftmals früher an wichtige Informationen kommen aber nicht sofort 
alles kaufen oder verkaufen können, weil es dann sofort alle anderen mitbekommen würden. Daher gibt es oft eine
langsame Entwicklung im Chart, die durch die Werkzeuge sichtbar gemacht werden kann.
</p>

<h1>Reality Check &ndash; hält es, was es verspricht?</h1>
<p>
Die New York Times schrieb 2006 folgendes über Rule #1:
"Furthermore, there is nothing wrong with Mr. Town's logic about how to find good stocks, 
just as there is nothing wrong with many of the diet books out there. If you exercise more, 
eat less and switch to healthier foods, you will probably lose weight and feel better."
</p>
<p>
Wie so oft ist die Theorie Poesie &ndash; die Realität aber Prosa. Dennoch glauben wir von Rule1Tool, 
dass die 15% Rendite erreichbar sind, sofern man sich an die Regeln und Prinzipien von Regel Nummer 1 hält. 
Und genau hierbei möchte wir Sie mit Rule1Tool unterstützen.
</p>
<h1>Rule1Tool.com: Damit es wirklich funktioniert</h1>
<p>Rule1Tool ist eine kostenlose Online-Plattform, die es sich zum Ziel gemacht hat, 
alle wichtigen Werkzeuge für Regel1-Investoren zu vereinen und diese optimal bedienbar darzustellen.
Weitere Informationen und einen Überblick über die Funktionen von Rule1Tool finden Sie in der Tour.
</p>

<p>
<?php echo $this->link(
			$this->url(
				array(
					"language" => Zend_Registry::get('Zend_Locale')->getLanguage()), 
					"tour"), 
				$this->translate("Zur Tour &raquo;"),"abutton blue large");?>
				 
<?php 
echo $this->link(
		$this->url(array("language" => Zend_Registry::get('Zend_Locale')->getLanguage()),
		 "user_register"), $this->translate("Zur Registrierung &raquo;"),"abutton blue large");?> 

</p>

<h1>Weiterführende Links</h1>
<ul>
<li><a href="http://www.regel1investor.de">Deutsches Forum zu Regel Nummer 1</a></li>
<li><a href="http://www.amazon.de/Regel-Nummer-Einfach-erfolgreich-anlegen/dp/3938350342">Bei Amazon kaufen</a></li>
<li><a href="http://www.ruleoneinvestor.com/">Website von Phil Town</a></li>
<li><a href="http://en.wikipedia.org/wiki/Phil_Town">Wikipedia-Artikel über Phil Town</a></li>
</ul>
