<h1>Sitemap</h1>
<h2>deutsch</h2>
<ul>
<li><?php 
echo $this->link(
		$this->url(array("language" => "de"),
		 "user_register"), "Registrierung");?></li>
<li>
<?php 
echo $this->link(
		$this->url(array("language" => "de"),
		 "tour"), "Tour");?></li>
<li><?php 
echo $this->link(
		$this->url(array("language" => "de"),
		 "rule1infosde"), "Regel 1 Informationen");?></li>
<li><?php 
echo $this->link(
		$this->url(array("language" => "de"),
		 "paybacktimeinfosde"), "Payback Time Informationen");?></li>

</ul>