<?php 
echo $this->messageBox($this->mbox);
echo $this->clearDiv();
?>
<div style="margin:30px 100px;">
<?php 
if(isset($this->params["fromAuth"]) && $this->params["fromAuth"] == true)
{
?>
<h2><?= $this->translate("Die angeforderte Seite ist nur für registrierte Mitglieder zugänglich. Bitte melden Sie sich an."); ?></h2>
<?php 
}
?>

<img src="<?php echo $this->baseUrlShort();?>/public/images/warnschild.png" style="float:left;margin:42px 25px;"/>
<form name="login" action="<?php echo $_SERVER["REQUEST_URI"];?>" method="POST">

    <table cellspacing=8 class="login modernForm">
    <tr>
	<td><strong><?= $this->translate("Anmelden");?></strong></td> 
    </tr>
	<tr>
		<td><input id="email" type="email" name="email" value="<?= $this->translate("E-Mail-Adresse");?>" onfocus="if(this.value == '<?= $this->translate("E-Mail-Adresse");?>') {this.value='';}this.style.color='#333';" 
onblur="if(this.value == '') {this.value='<?= $this->translate("E-Mail-Adresse");?>';this.style.color='#b9b9b9';}" /></td> 
	</tr>
	<tr>
		<td><input id="password" type="password" name="password" value="<?= $this->translate("Kennwort");?>" onfocus="if(this.value == '<?= $this->translate("Kennwort");?>') {this.value='';}this.style.color='#333';" 
onblur="if(this.value == '') {this.value='<?= $this->translate("Kennwort");?>';this.style.color='#b9b9b9';}" /><br/>
		<small><?php echo $this->link($this->url(array("language" => Zend_Registry::get('Zend_Locale')->getLanguage()), "user_resetpw"), $this->translate("Kennwort vergessen?"));?></small></td> 
    </tr>
    <tr>
	<td><input id="submit" type="SUBMIT" value="<?= $this->translate("» Anmelden");?>"></td> 
    </tr>
    </table>

</form>
</div>