<div class="contentContainer">
<h1><?php echo $this->translate("Kennwort anfordern");?></h1>
<p class="h2InfoLine"><?php echo $this->translate("Sie haben Ihr Kennwort vergessen? Kein Problem! Geben Sie einfach Ihre E-Mail-Adresse an, mit der Sie sich bei Rule1Tool registriert haben, und wir senden Ihnen sofort ein neues Kennwort per Mail.");?></p>
<?php 
if($this->mbox)
echo $this->messageBox($this->mbox, "input");
echo $this->clearDiv();
?>
<?php echo $this->form;?>
</div>