<h1 style="font-size:1.5em;
	line-height:1.8em;
	margin:0px;"><?php echo $this->translate("Eine neue Nachricht liegt vor");?></h1>

<p style="margin:0px 0px 5px;">
<?php echo $this->translate("Name");?>: <?php echo $this->data["name"]?><br/>
<?php echo $this->translate("E-Mail");?>: <?php echo $this->data["email"]?><br/>
<br/>
<?php echo $this->translate("Nachricht");?>: <?php echo $this->data["text"]?><br/>
</p>
