<h1 style="font-size:1.5em;
	line-height:1.8em;
	margin:0px;"><?php echo $this->translate("Ihr neues Kennwort");?></h1>
<p style="font-size:1.2em;
	line-height:1.6em;
	margin:0px 0px 8px;"><?php echo $this->translate("Ihr Kennwort wurde zurückgesetzt. Sie können sich mit dem unten angegebenen Kennwort bei Rule1Tool anmelden und dann selbstständig ein neues Kennwort setzen.");?>
</p>
<p style="margin:20px 0px;">
<?php echo $this->translate("Ihr neues Kennwort:");?> <strong><?php echo $this->data["password"]?></strong>
</p>

<p style="margin:0px 0px 5px;">
<?php echo $this->translate("Eigenes Kennwort setzen:");?><br/>
<a href="<?php echo "http://".$_SERVER["SERVER_NAME"].
$this->url(array("language" => Zend_Registry::get('Zend_Locale')->getLanguage(), "username" => $this->data["username"]), "user_profile");?>
"><?php echo "http://".$_SERVER["SERVER_NAME"].
$this->url(array("language" => Zend_Registry::get('Zend_Locale')->getLanguage(), "username" => $this->data["username"]), "user_profile");?></a>
</p>
<p style="margin:10px 0px 5px;"><?php echo $this->translate("Ihr Rule1Tool Team");?>
</p>
